#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <wx/msgdlg.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void WindowSizeChanged( wxSizeEvent& event );
		void WindowUpdate( wxUpdateUIEvent& event );
		void WczytajObrazekClick( wxCommandEvent& event );
		void CenzuraClick( wxCommandEvent& event );
		void ErodeClick( wxCommandEvent& event );
		void AnimacjaCheck( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

		// obrazek
		wxImage image;
		wxImage copy;

		bool anim = false;

		// rozmiary
		int window_width;
		int window_height;
		// do rysowania co sie dzieje
		wxString path;
		void Repaint();
};

#endif // __GUIMyFrame1__
